- hosts: localhost
  tasks:
  - name: launching instance
    ec2:
      instance_type: "t2.micro"
      image: "ami-0a780d5bac870126a"
      key_name: "RHEL"
      wait: yes
      count: 1
      vpc_subnet_id: "subnet-f30b079b"
      assign_public_ip: yes
      region: "ap-south-1"
      state: present
      group_id: "sg-060fbc90ebc18ff1c"
      aws_access_key: "YOUR ACCESS KEY"
      aws_secret_key: "YOUR SECRET KEY"

